### PR TITLE
fix: do not invalidate recovery addr on update

### LINKED ISSUE #2433: Admin API identity update invalidates recovery link
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] #2646

### Describe the bug

Hey,

I encountered a problem: when an identity gets updated (via admin endpoint) during account recovery,
the recovery flow get invalidated. Is this working as expected?

### Reproducing the bug

1. Create an identity via admin endpoint
2. Initiate self service recovery flow so an email with recovery link gets sent out
3. Update same identity via admin endpoint with no changes (same traits, state == active, same schema)
4. Follow the recovery link received in email
5. Get a flow response that the recovery token is invalid

### Relevant log output

_No response_

### Relevant configuration

```yml
identity schema:

{
  "$id": "identity0",
  "title": "Test",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "recovery": {
              "via": "email"
            },
            "verification": {
              "via": "email"
            }
          }
        }
      },
      "required": [
        "email"
      ],
      "additionalProperties": false
    }
  }
}
```

### Version

v0.9.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker

### Additional Context

If there is no identity update via admin endpoint between the recovery link getting sent out and clicked, the whole recovery and password reset flow works correctly.

If this is a problem because the admin endpoint updates the whole identity, maybe the recovery link could stay valid if there are no changes in the update.

### PR DESCRIPTION
**Pull request by hperl**
This PR modifies persister.UpdateIdentity to only update the recovery addresses that changed, leaving the unchanged once (and their associated recovery tokens) valid.

Shout-out to @thcyron for the analysis.

Fixes #2433

---

## TODO

- [x] Is everything Go 1.18 ready? (CI, Docker, ...)

### CODE REVIEW

File: persistence/sql/persister_identity.go [hunk 1]
```diff
@@ -202,6 +202,43 @@ func (p *Persister) createVerifiableAddresses(ctx context.Context, i *identity.I
 	return nil
 }
 
+func (p *Persister) updateRecoveryAddresses(ctx context.Context, i *identity.Identity) error {
```
Comment (aeneasr) [inline persistence/sql/persister_identity.go:205]: This probably needs some tests to ensure the diff is applied correctly :)

**Review by aeneasr — CHANGES_REQUESTED** [review]
Thank you for the quick turnaround! We have the problem both in recovery as well as verification :) It would also be awesome if we could write a small test to ensure that the diff is working correctly. Speaking about this, it's not uncommon that we need to check whether a `1:n` relationship has changed in Ory Kratos (same goes for credentials for example) so maybe we can generalize this problem using a (potentially generic) diff function to return the IDs that need to be removed and inserted?

File: persistence/sql/persister_identity.go (hunk 1 above)
Comment (hperl) [reply persistence/sql/persister_identity.go:205]: Thanks, makes sense. I only tested for the actual bug for now, but I can extend this to all relationships.

Comment (hperl) [reply persistence/sql/persister_identity.go:205]: I just looked at the existing tests, and we already test that `UpdateIdentity` propagates updates to the recovery address here:

https://github.com/ory/kratos/blob/a059ef079ceffdec6364e174e782b171cbbdc25b/identity/test/pool.go#L769-L803

Comment (aeneasr) [reply persistence/sql/persister_identity.go]: 👍 perfect

**Review by aeneasr — DISMISSED** [review]

File: persistence/sql/persister_identity.go [hunk 2]
```diff
@@ -192,24 +192,83 @@ func (p *Persister) createVerifiableAddresses(ctx context.Context, i *identity.I
...
+	}
+
+	// Subtle: we delete the old associations from the DB first, because else
+	// they could cause UNIQUE constraints to fail on insert.
+	for h, a := range oldAssocs {
+		if _, found := newAssocs[h]; found {
+			newAssocs[h] = nil // Ignore associations that are already in the db.
+		} else {
+			if err := p.GetConnection(ctx).Destroy(a); err != nil {
+				return err
```
Comment (aeneasr) [inline persistence/sql/persister_identity.go:230]: Please use `sqlcon.HandleError()`

File: persistence/sql/persister_identity.go [hunk 3]
```diff
@@ -192,24 +192,83 @@ func (p *Persister) createVerifiableAddresses(ctx context.Context, i *identity.I
...
+			}
+		}
+	}
+
+	for _, a := range newAssocs {
+		if a != nil {
+			if err := p.GetConnection(ctx).Create(a); err != nil {
+				return err
```
Comment (aeneasr) [inline persistence/sql/persister_identity.go:238]: Please use `sqlcon.HandleError()`

File: persistence/sql/persister_identity.go [hunk 4]
```diff
@@ -350,27 +411,25 @@ func (p *Persister) UpdateIdentity(ctx context.Context, i *identity.Identity) er
...
 
-		if err := p.createVerifiableAddresses(ctx, i); err != nil {
+		/* #nosec G201 TableName is static */
+		if err := tx.RawQuery(
+			fmt.Sprintf(
+				`DELETE FROM %s WHERE identity_id = ? AND nid = ?`,
+				new(identity.Credentials).TableName(ctx)),
+			i.ID, p.NetworkID(ctx)).Exec(); err != nil {
+
 			return err
```
Comment (aeneasr) [inline persistence/sql/persister_identity.go:429]: `sqlcon.HandleError()`

**Comment by hperl** [comment]
@aeneasr all review comments addressed. As far as the test for the verified address go, the suite is very thorough:

https://github.com/ory/kratos/blob/bece07609f1d46f8e24da4f51468edbb4a8847b3/identity/test/pool.go#L555-L719

**Review by aeneasr — APPROVED** [review]
Great job :)
