### PR TITLE
docs: schema fixes

### LINKED ISSUE #2357: Docs: messages are not required
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

~The `messages` field of the `uiNode` is marked as `required` in the HTTP API documentation. However, the field is not returned when getting a registration flow via `/self-service/registration/flows`.~

### Relevant log output

_No response_

### Relevant configuration

_No response_

### Version

v0.9.0-alpha.3

### On which operating system are you observing this issue?

_No response_

### In which environment are you deploying?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by woylie**
This PR updates the API schema.

resolves #2357 

- [x] turn `uiNodeType` into enum
- [x] turn `uiNodeGroup` into enum
- [x] ensure select field value for `attributes.node_type` matches actual node_type value (see screenshot)
- [x] add task for previewing API documentation
- [x] In `api.openapi.json`, the `LoginFlow` and the `VerificationFlow` list `type` as a required property. The other flows don't, and none of the flows in `openapi.json` list it. I assume the type should always be set to either `"api"` or `"browser"` and never be omitted or `null`. Is that so? If so, I'll add `type` as a required property to all the flows.

imagen

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Review by zepatrik — CHANGES_REQUESTED** [review]
Thanks for the PR. Unfortunately, this will not fix the problem as we generate the openapi schema from comments in the code. Instead, you will have to find and fix those.
Specifically you want to adjust https://github.com/ory/kratos/blob/37f2f220ce699e031018777c9976cafa22faa984/ui/node/attributes.go#L84-L114

Enums can be created like this: https://github.com/ory/keto/blob/d64ae29b5aa7359792c3515a771eefc093065f9b/internal/expand/tree.go#L15-L23

So you have to adjust https://github.com/ory/kratos/blob/37f2f220ce699e031018777c9976cafa22faa984/ui/node/node.go#L20-L21 to follow the structure of the other sample. It is specifically important to put the consts just below the type definition in one const group.

You can test if your changes work by running `make sdk`.

**Comment by woylie** [comment]
Thanks, I'll revise this tomorrow.

**Comment by woylie** [comment]
I'm sorry, I'm not very familiar with Go and I don't know what I'm doing. The output still looks wrong.

**Comment by zepatrik** [comment]
> Thanks, I'll revise this tomorrow.

That was a short night :wink: 

Swagger, the tool we use for generating the spec, is unfortunately very buggy. I think it only works if the enum name and the type name is the same. I'll quickly try that.

**Comment by zepatrik** [comment]
> One more question, what is the reason for all the HTML tags like <code type="make/command">make test-docs</code> in the readme, instead of just using backticks and code fences?

That's related to a tool we use for testing documentation https://github.com/kevgo/text-runner

File: Makefile [hunk 1]
```diff
@@ -39,6 +39,14 @@ $(call make-lint-dependency)
 docs/cli:
 		go run ./cmd/clidoc/. .
 
+.PHONY: docs/api
+docs/api:
+		npx @redocly/openapi-cli preview-docs spec/api.json
+
+.PHONY: docs/swagger
+docs/swagger:
+		npx @redocly/openapi-cli preview-docs spec/swagger.json
```
Comment (zepatrik) [inline Makefile:48]: Oh that's nice :+1:

**Review by zepatrik — APPROVED** [review]
Nice, looks good to me. The CI failure does not seem related, but maybe rebase onto current master and let it run again?

File: ui/node/node.go [hunk 2]
```diff
@@ -17,34 +17,39 @@ import (
 	"github.com/ory/x/stringslice"
 )
 
-// swagger:model uiNodeType
+// swagger:enum Type
```
Comment (aeneasr) [inline ui/node/node.go:20]: Could we name this

```suggestion
// swagger:enum UiNodeType
```

please?

File: ui/node/node.go [hunk 3]
```diff
@@ -17,34 +17,39 @@ import (
...
 	Image  Type = "img"
 	Anchor Type = "a"
 	Script Type = "script"
 )
 
+func (t Type) String() string {
+	return string(t)
+}
+
+// swagger:enum Group
```
Comment (aeneasr) [inline ui/node/node.go:35]: Could we name this

```suggestion
// swagger:enum UiNodeGroup
```

please?

**Review by aeneasr — CHANGES_REQUESTED** [review]
This is grand, thank you! Just two comments :)

File: ui/node/node.go (hunk 2 above)
Comment (woylie) [reply ui/node/node.go:20]: I would have to rename both the Swagger enum name and the actual Go type (`type UiNodeType string`), otherwise Swagger will not generate the spec correctly. Is that what you want?

Comment (aeneasr) [reply ui/node/node.go:20]: I see, yes that would be ok. The problem is that this will end up with `EnumType` in most generators, which is not unique enough and will cause issues when we have multiple enums called `type` - something that is quite likely to happen :)

Comment (woylie) [reply ui/node/node.go]: Done!

**Review by aeneasr — APPROVED** [review]
Awesome, thank you! 🎉 Your contribution makes Ory better :)

**Comment by vinckr** [comment]
Hello @woylie 
Congrats on merging your first PR in Ory 🎉 !
Your contribution will soon be helping secure millions of identities around the globe 🌏. 
As a small token of appreciation we send all our first time contributors a gift package to welcome them to the community. 
[Please drop me an email and I will forward you the form to claim your Ory swag!](mailto:vincent@ory.sh)
