### PR TITLE
fix: insert credentials type constants as part of migrations

### LINKED ISSUE #861: Kratos Admin API return 409 when createIdentity is called simultaneously
When the Kratos Typescript client Admin API's createIdentity method is called simultaneously with a freshly started Kratos instance (without any identities in the database), error 409 is returned as follows:

```
error: {
  code: 409,
  status: 'Conflict',
  message: 'failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: duplicate key value violates unique constraint "identity_credential_types_name_idx" (SQLSTATE 23505): Unable to insert or update resource because a resource with that value exists already'
}
```

It seems like when Kratos creates the first user, it inserts the entry for the credential type (in my case it's "password") in the identity_credential_types table. With multiple requests at the same time, it tries to insert the same entry multiple times and fails.

**Reproducing the bug**

1. Start Kratos
1. Call the Kratos createIdentity client simulatenously e.g. using the example code below
1. Most of the time but not always, Kratos throws the error

Client code that makes requests to my server that then calls Kratos:
```
  await Promise.all(usersToAdd.map(async (user) => {
    console.log('Adding user', user);
    return await graphQl('createLocalUser', {
      input: {
        email: user.email,
        firstName: user.firstName,
        lastName: user.lastName,
        type: 'local',
        password: user.password || 'secret',
      },
    }, token);
  }));
```

Method in my server that calls Kratos:
```
  public async createIdentity(email: string, firstName: string, lastName: string): Promise<string> {
    try {
      const id: CreateIdentity = {
        schema_id: `default`,
        traits: {
          name: {
            last: lastName,
            first: firstName,
            // second: 'hello',
          },
          email: email,
        },
      };
      logger.debug('Create Kratos identity: %O', id);
      const response = await this.adminEndpoint.createIdentity(id);
      return response.data.id;
    } catch (error) {
      if (error?.statusCode==409) {
        logger.error('User already exist in Kratos');
        throw new Error('User already exist in Kratos');
      }
      logger.error('Could not create Kratos user: %O', error.response?.data?.error?.message);
      throw new Error(error.response?.data?.error?.message);
    }
  }
```

_Server logs_
```
ion=
kratos_1             | time=2020-11-28T22:44:29Z level=info msg=No tracer configured - skipping tracing setup audience=application service_name=kratos service_version=
kratos_1             | time=2020-11-28T22:44:29Z level=info msg=Starting the public httpd on: 0.0.0.0:4433 audience=application service_name=kratos service_version=
kratos_1             | time=2020-11-28T22:44:29Z level=info msg=Starting the admin httpd on: 0.0.0.0:4434 audience=application service_name=kratos service_version=
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=started handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43526 request=/identities
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=started handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43528 request=/identities
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=started handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43530 request=/identities
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=started handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43532 request=/identities
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=started handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43542 request=/identities
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=completed handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43526 request=/identities status=201 text_status=Created took=46.1414ms
kratos_1             | time=2020-11-28T22:45:16Z level=error msg=An error occurred while handling a request audience=application error=map[debug: message:failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: duplicate key value violates unique constraint "identity_credential_types_name_idx" (SQLSTATE 23505): Unable to insert or update resource because a resource with that value exists already reason: status:Conflict status_code:409] http_request=map[headers:map[accept:application/json, text/plain, */* user-agent:axios/0.19.2] host:kratos:4434 method:POST path:/identities query:<nil> remote:192.168.16.7:43530 scheme:http] http_response=map[status_code:409] service_name=kratos service_version=
kratos_1             | time=2020-11-28T22:45:16Z level=error msg=An error occurred while handling a request audience=application error=map[debug: message:failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: duplicate key value violates unique constraint "identity_credential_types_name_idx" (SQLSTATE 23505): Unable to insert or update resource because a resource with that value exists already reason: status:Conflict status_code:409] http_request=map[headers:map[accept:application/json, text/plain, */* user-agent:axios/0.19.2] host:kratos:4434 method:POST path:/identities query:<nil> remote:192.168.16.7:43532 scheme:http] http_response=map[status_code:409] service_name=kratos service_version=
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=completed handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43532 request=/identities status=409 text_status=Conflict took=46.0482ms
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=completed handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43530 request=/identities status=409 text_status=Conflict took=45.9592ms
kratos_1             | time=2020-11-28T22:45:16Z level=error msg=An error occurred while handling a request audience=application error=map[debug: message:failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: duplicate key value violates unique constraint "identity_credential_types_name_idx" (SQLSTATE 23505): Unable to insert or update resource because a resource with that value exists already reason: status:Conflict status_code:409] http_request=map[headers:map[accept:application/json, text/plain, */* user-agent:axios/0.19.2] host:kratos:4434 method:POST path:/identities query:<nil> remote:192.168.16.7:43528 scheme:http] http_response=map[status_code:409] service_name=kratos service_version=
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=completed handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43528 request=/identities status=409 text_status=Conflict took=49.5882ms
kratos_1             | time=2020-11-28T22:45:16Z level=error msg=An error occurred while handling a request audience=application error=map[debug: message:failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: duplicate key value violates unique constraint "identity_credential_types_name_idx" (SQLSTATE 23505): Unable to insert or update resource because a resource with that value exists already reason: status:Conflict status_code:409] http_request=map[headers:map[accept:application/json, text/plain, */* user-agent:axios/0.19.2] host:kratos:4434 method:POST path:/identities query:<nil> remote:192.168.16.7:43542 scheme:http] http_response=map[status_code:409] service_name=kratos service_version=
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=completed handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43542 request=/identities status=409 text_status=Conflict took=27.7992ms

```

_Server configuration_

```yaml
log:
  level: debug
  format: text

dsn: postgres://kratos:kratos@postgres:5432/kratos?sslmode=disable

serve:
  public:
    base_url: http://localhost:10020/.ory/kratos/public/
  admin:
    base_url: http://kratos:4434/

identity:
  default_schema_url: file:///etc/config/kratos/identity.traits.schema.json

selfservice:
  default_browser_return_url: http://localhost:10020/
  whitelisted_return_urls:
    - http://localhost:10020

  methods:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: azure-ad
            provider: microsoft
            client_id: SECRET
            client_secret: SECRET
            tenant: common
            mapper_url: file:///etc/config/kratos/oidc.azure-ad.jsonnet
            scope:
              - profile
              - email

  flows:
    error:
      ui_url: http://localhost:10020/error
    settings:
      ui_url: http://localhost:10020/settings
      privileged_session_max_age: 15m
    recovery:
      enabled: true
      ui_url: http://localhost:10020/recovery
    verification:
      enabled: false
      ui_url: http://localhost:10020/verify
      after:
        default_browser_return_url: http://localhost:10020/
    logout:
      after:
        default_browser_return_url: http://localhost:10020/auth/login
    login:
      ui_url: http://localhost:10020/auth/login
      lifespan: 100m
    registration:
      lifespan: 100m
      ui_url: http://localhost:10020/auth/register
      after:
        password:
          hooks:
            - hook: session
        oidc:
          hooks:
            - hook: session

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

hashers:
  argon2:
    parallelism: 1
    memory: 16384
    iterations: 4
    salt_length: 16
    key_length: 16

courier:
  smtp:
    connection_uri: smtps://foo:bar@my-mailserver:1234/?skip_ssl_verify=false
```

**Traits Schema**
```
{
  "$id": "https://myrandomcompany.com/server/kratos/default/identity.traits.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "minLength": 3,
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "recovery": {
              "via": "email"
            }
          }
        },
        "name": {
          "type": "object",
          "properties": {
            "first": {
              "type": "string"
            },
            "last": {
              "type": "string"
            }
          }
        },
        "phone_number": {
          "type": "string"
        }
      },
      "required": [
        "email"
      ],
      "additionalProperties": false
    }
  }
}
```

**Expected behavior**
The users should have been created without errors.

**Environment**
WSL-2
Docker compose

**Additional context**
Kratos image tag: v0.5.4
Kratos typescript client version: 0.5.4-alpha.1

### PR DESCRIPTION
**Pull request by zepatrik**
## Related issue

closes #861 

## Proposed changes

Raise transaction isolation level to ensure only one transaction creates the credential type.

## Further comments

This is not yet working with sqlite because it is not automatically queuing transactions, I will find a way around that tomorrow.

### CODE REVIEW

**Comment by aeneasr** [comment]
@zepatrik tests fail

**Comment by zepatrik** [comment]
I know, that's why I wrote

| This is not yet working with sqlite because it is not automatically queuing transactions, I will find a way around that tomorrow.

File: internal/testhelpers/sql.go [hunk 1]
```diff
@@ -26,21 +26,34 @@ func CleanSQL(t *testing.T, c *pop.Connection) {
 
 		new(login.FlowMethods).TableName(),
 		new(login.Flow).TableName(),
+		"selfservice_login_request_methods",
+		"selfservice_login_requests",
```
Comment (zepatrik) [inline internal/testhelpers/sql.go:30]: I had to add all of these tables because rerunning the tests locally did not work otherwise. Am I missing something?

Comment (aeneasr) [reply internal/testhelpers/sql.go:30]: Hm they should be removed by the migration itself. I don't think they need to be added?

Comment (zepatrik) [reply internal/testhelpers/sql.go:30]: I get a `table already exists` error without adding them here. `CleanSQL` is not running down migrations but drops all tables, seems like some were missing here. Or what do you mean by "removed by the migration itself"?

Comment (aeneasr) [reply internal/testhelpers/sql.go:30]: Is `CleanSQL` called for the migration tests? If so, I think these need to stay. What I meant was that these tables are renamed/removed by the SQL Migrations (they are renamed to `selfservice_login_flows` for example).

File: persistence/sql/persister.go [hunk 2]
```diff
@@ -56,7 +56,11 @@ func (p *Persister) MigrateDown(ctx context.Context, steps int) error {
 }
 
 func (p *Persister) MigrateUp(ctx context.Context) error {
-	return errors.WithStack(p.mb.Up())
+	if err := p.mb.Up(); err != nil {
+		return errors.WithStack(err)
+	}
+
+	return identity.GuaranteeCredentialTypes(p.c)
```
Comment (aeneasr) [inline persistence/sql/persister.go]: Shouldn't this be just it's own SQL Migration? Why is it handled in the code?

Comment (zepatrik) [reply persistence/sql/persister.go]: I wanted to make sure that we don't have to duplicate the data into sql and forget to update it there. But it makes more sense, if one would be renamed we would have to do it in a migration. I will change it and add tests to check whether the migration adds the correct data.

Comment (aeneasr) [reply persistence/sql/persister.go]: Ooops missed that!

Comment (zepatrik) [reply persistence/sql/persister.go]: Missed what?

File: internal/testhelpers/sql.go (hunk 1 above)
Comment (zepatrik) [reply internal/testhelpers/sql.go:30]: Ok could not reproduce with clean databases. I probably killed the test in the middle of migrations at some point.

File: persistence/sql/persister.go (hunk 2 above)
Comment (aeneasr) [reply persistence/sql/persister.go]: Sorry I got confused with the notification emails. Yes please do it as a migration. It is cleaner and allows for updates.

**Comment by aeneasr** [comment]
@zepatrik good for 👀 ?

**Comment by zepatrik** [comment]
Yes, always :wink:

File: persistence/sql/migratest/testdata/20200402142539_testdata.sql [hunk 3]
```diff
@@ -11,7 +11,7 @@ INSERT INTO courier_messages (id, type, status, body, subject, recipient, create
...
 INSERT INTO courier_messages (id, type, status, body, subject, recipient, created_at, updated_at) VALUES ('a3ea4c30-0c6e-47b1-99ba-8fa69282e166', 1, 2, 'Hi, please verify your account by clicking the following link: <a href="http://127.0.0.1:4455/.ory/kratos/public/self-service/browser/flows/verification/email/confirm/AtsREGbtXu0RlIcwv3RPpxHEZNEcq3R9">http://127.0.0.1:4455/.ory/kratos/public/self-service/browser/flows/verification/email/confirm/AtsREGbtXu0RlIcwv3RPpxHEZNEcq3R9</a>', 'Please verify your email address', 'foo@ory.sh', '2013-10-07 08:23:19', '2013-10-07 08:23:19');
 
-INSERT INTO identity_credential_types (id, name) VALUES ('22bff9ae-f5aa-45d7-803b-97ec0b4e7b32', 'password');
+INSERT INTO identity_credential_types (id, name) VALUES ('22bff9ae-f5aa-45d7-803b-97ec0b4e7b32', 'not password');
```
Comment (aeneasr) [inline persistence/sql/migratest/testdata/20200402142539_testdata.sql:14]:
```suggestion
INSERT INTO identity_credential_types (id, name) VALUES ('22bff9ae-f5aa-45d7-803b-97ec0b4e7b32', 'password');
```

File: persistence/sql/migrations/sql/20201201161451_credential_types_values.up.sql [hunk 4]
```diff
@@ -0,0 +1,5 @@
+INSERT INTO identity_credential_types
```
Comment (aeneasr) [inline persistence/sql/migrations/sql/20201201161451_credential_types_values.up.sql:1]: Only insert if not exists

**Review by aeneasr — CHANGES_REQUESTED** [review]

**Review by aeneasr — APPROVED** [review]
