### PR TITLE
fix: correctly apply patches to identity metadata

### LINKED ISSUE #2950: Can't update metadata with patch
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Not sure whether it's a bug, or not supported (the HTTP API docs don't mention metadata patching not being supported, though), or whether I'm doing something wrong. I'm trying to update a single `metadata_admin` field via the identity patch endpoint, but depending on the JSON patch operation I use, I'm either getting an error or the metadata is set to `NULL`.

### Reproducing the bug

1. create an identity with `metadata_admin` set to `{"state_detailed": "active"}`
2. `PATCH /admin/identities/{id}` with this request body:

```json
[
  {
    "op": "replace",
    "path": "/state",
    "value": "inactive"
  },
  {
    "op": "add",
    "path": "/metadata_admin/state_detailed",
    "value": "suspended"
  }
]
```

This results in the error `add operation does not apply: doc is missing path: \"/metadata_admin/state_detailed\": missing value`.

On the other, when I run the request with this request body:

```json
[
  {
    "op": "replace",
    "path": "/state",
    "value": "inactive"
  },
  {
    "op": "add",
    "path": "/metadata_admin",
    "value": {
      "state_detailed": "suspended"
    }
  }
]
```

I'm getting a success respone, but now `metadata_admin` is `NULL` in the database (same with replace). 

### Relevant log output

_No response_

### Relevant configuration

_No response_

### Version

0.11.0

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jonas-jonas**
## Related issue(s)

Fixes #2950

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

File: identity/handler_test.go [hunk 1]
```diff
@@ -524,191 +524,233 @@ func TestHandler(t *testing.T) {
...
-				})
-			}
-		})
+		for name, ts := range map[string]*httptest.Server{"public": publicTS, "admin": adminTS} {
+			t.Run("endpoint="+name, func(t *testing.T) {
+				patch := []patch{
+					{"op": "replace", "path": "/metadata_admin/allowed", "value": "false"},
+				}
 
-		t.Run("case=should delete a user and no longer be able to retrieve it", func(t *testing.T) {
```
Comment (jonas-jonas) [inline identity/handler_test.go:703]: Moved a few tests around, as they weren't in the right sub-test anyway. Probably best to review without whitespace changes.

**Review by aeneasr — APPROVED** [review]
