### PR TITLE
fix: Run post recovery hook before storing the session and issuing a cookie

### LINKED ISSUE #3193: Flow interrupting in after recovery webhook does not work
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

According to the docs at https://www.ory.sh/docs/guides/integrate-with-ory-cloud-through-webhooks#flow-interrupting-webhooks it should be possible to interrupt a flow by returning an error code from the webhook. This works for the registration but not the recovery flow.

### Reproducing the bug

1. Apply the provided configuration
2. Perform the recovery flow and have the webhook return a 400 status code (with a properly formatted error payload)
3. Observe that the flow does not get interrupted

### Relevant log output

```shell
time=2023-03-28T11:26:39Z level=debug msg=A recovery flow is being retried because a validation error occurred. audience=application error=map[message:1 validation errors occurred:
(0) I[#/traits/email] S[] a webhook target returned an error stack_trace:
github.com/ory/kratos/schema.NewValidationListError
	/go/src/github.com/ory/kratos/schema/errors.go:274
github.com/ory/kratos/selfservice/hook.parseWebhookResponse
```

### Relevant configuration

```yml
selfservice:
  flows:
    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery
      use: code
      after:
        hooks:
          - hook: web_hook
            config:
              url: http://127.0.0.1:8080/ory/recovery
              method: POST
              body: file:///etc/kratos/config/webhook.body.jsonnet
              response:
                parse: true
```

### Version

master (b69981a2cfa68de6e47561d9f4e3a04d9297557e)

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by BrandonNoad**
If the response to a flow-interrupting, after recovery webhook is `4xx` or `5xx`, the recovery flow should fail and no session should be issued.

## Related issue(s)

Fixes #3193

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

**Review by zepatrik — COMMENTED** [review]
It would be great to add a test that verifies this behavior. As all other tests are passing, it seems that at least it is not breaking anything.

**Comment by BrandonNoad** [comment]
@zepatrik Definitely. I wanted to make sure the existing tests were passing and haven't had the chance yet to add the new tests. I'll remove the `[WIP]` from the PR title when it is ready (I would have made this a draft but wasn't sure if the tests would run or not).

File: selfservice/strategy/code/strategy_recovery_test.go [hunk 1]
```diff
@@ -1055,6 +1055,72 @@ func TestRecovery(t *testing.T) {
...
+
+		body = submitRecoveryCode(t, cl, body, RecoveryFlowTypeBrowser, recoveryCode, http.StatusSeeOther)
+
+		require.Len(t, cl.Jar.Cookies(urlx.ParseOrPanic(public.URL)), 2)
+		cookies := spew.Sdump(cl.Jar.Cookies(urlx.ParseOrPanic(public.URL)))
+		assert.Contains(t, cookies, "ory_kratos_session")
+	})
+
+	t.Run("description=should not be able to recover if post recovery hook fails", func(t *testing.T) {
+		conf.MustSet(ctx, config.HookStrategyKey(config.ViperKeySelfServiceRecoveryAfter, config.HookGlobal), []config.SelfServiceHook{{Name: "err", Config: []byte(`{"ExecutePostRecoveryHook": "err"}`)}})
```
Comment (BrandonNoad) [inline selfservice/strategy/code/strategy_recovery_test.go:1092]: I couldn't figure out a good way to mock a 4xx response to the webhook request so that I could test the message in the response would show up in the new flow.

**Comment by BrandonNoad** [comment]
Technically this change could be considered breaking. But I think it is just restoring the intended behaviour.

**Review by zepatrik — APPROVED** [review]
Looks very good, I think this error should be enough.

**Review by hperl — APPROVED** [review]
LGTM!
