### PR TITLE
fix: de-duplicate message IDs

### LINKED ISSUE #1956: Conflicting message IDs for node and verification
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The message IDs in the files `text/message_verification.go` and `text/message_node.go` start at the same ID `1070000`, hence there are conflicting IDs. This causes a problem when implementing custom translations in the _self-service UI_, because messages can not identified uniquely.

See:
* https://github.com/ory/kratos/blob/fc17cf8737ff6ebbe00be8399b1a423a0888b670/text/message_node.go#L4
* https://github.com/ory/kratos/blob/a307deb6779dacd2ce54e161a00d347600d2c583/text/message_verification.go#L9

### Reproducing the bug

No specific steps are needed.

### Relevant log output

_No response_

### Relevant configuration

_No response_

### Version

v0.8.0-alpha.3 (master)

### On which operating system are you observing this issue?

_No response_

### In which environment are you deploying?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by zepatrik**
## Related issue(s)

closes #1956 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

## Further Comments

The clidoc util now ensures that there are no duplicate IDs.
It works, as before changing the ID I got this error:
```
$ make docs/cli
go run ./cmd/clidoc/. .
Unable to validate messages: message ID 1070000 is used more than once: InfoSelfServiceVerification InfoNodeLabel
main.validateAllMessagesExist
        /home/patrik/git/kratos/cmd/clidoc/main.go:267
main.main
        /home/patrik/git/kratos/cmd/clidoc/main.go:127
runtime.main
        /usr/lib/go/src/runtime/proc.go:255
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1581
exit status 1
make: *** [Makefile:33: docs/cli] Error 1
```

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -29,10 +29,12 @@ $(foreach dep, $(GO_DEPENDENCIES), $(eval $(call make-go-dependency, $(dep))))
...
 
 .bin/clidoc:
+		echo "deprecated usage, use docs/cli instead"
 		go build -o .bin/clidoc ./cmd/clidoc/.
 
-docs/cli: .bin/clidoc
-		clidoc .
+.PHONY: docs/cli
+docs/cli:
+		go run ./cmd/clidoc/. .
```
Comment (zepatrik) [inline Makefile:37]: This is way easier to manage.

File: cmd/clidoc/main.go [hunk 2]
```diff
@@ -192,25 +194,82 @@ func writeMessages(path string) error {
...
+					if _, ok := messages[name]; !ok {
+						return errors.Errorf("expected to find message %s in the list for the documentation generation but could not", name)
+					}
+				}
+			case *ast.GenDecl:
+				if decl.Tok == token.CONST {
+					for _, spec := range decl.Specs {
+						value := spec.(*ast.ValueSpec) // safe because decl.Tok is token.CONST
+						if t, ok := value.Type.(*ast.Ident); ok {
+							if t.Name == "ID" {
```
Comment (zepatrik) [inline cmd/clidoc/main.go:242]: This filters to use const's only of type `ID` (i.e. hard-coded).

File: cmd/clidoc/main.go [hunk 3]
```diff
@@ -192,25 +194,82 @@ func writeMessages(path string) error {
...
+			break
+		}
+	}
+	allFiles := make([]*ast.File, 0)
+	for fn, f := range pack.Files {
+		if strings.HasSuffix(fn, "/id.go") {
+			allFiles = append(allFiles, f)
+		}
+	}
+	_, err = (&types.Config{Importer: importer.Default()}).Check("text", set, allFiles, info)
```
Comment (zepatrik) [inline cmd/clidoc/main.go:223]: This gave me a bit of a hard time, as I could not get it to properly resolve imports from modules. Therefore, the warning in the `id.go` file.

File: cmd/clidoc/main.go [hunk 4]
```diff
@@ -192,25 +194,82 @@ func writeMessages(path string) error {
...
+	var pack *ast.Package
+	for _, p := range packs {
+		if p.Name == "text" {
+			pack = p
+			break
+		}
+	}
+	allFiles := make([]*ast.File, 0)
+	for fn, f := range pack.Files {
+		if strings.HasSuffix(fn, "/id.go") {
```
Comment (zepatrik) [inline cmd/clidoc/main.go:219]: and hence we only load that file (hard-coded).
